### ISSUE TITLE
Remove dependency on defining __file__

### ISSUE THREAD

**Issue by abid-mujtaba** [chmp/ipytest#13] opened 2019-01-25 16:23 UTC
Hi. I'm working on a custom [pytest kernel](https://github.com/abid-mujtaba/jupyter-pytest-kernel) for Jupyter Notebooks. It is simply a thin wrapper on the ipython3 kernel and uses your excellent package for all the heavy lifting.

My aim is to make using it transparent, meaning no extra code should be added by the user. I have used injection to achieve most of this goal with the sole exception of the `__file__` variable. I have a very crude hack that works around this.

What I was wondering, however, was if it could be possible to remove the dependency on defining `__file__` in the notebook. 

In particular some way to leverage the fact that I have access to the code being passed in to `do_execute()` in the kernel so can essentially store all the code in a string if `ipytest` can digest that directly without having to parse the .ipynb file that it needs to be passed in using `__file__`.

**Comment by chmp** [comment] 2019-01-29 18:14
Hi. Sounds great. Pytest never reads the notebook. The way it is implemented, ipytest passes the notebook file name to pytest, but then injects itself to directly return the `__main__` module. The issue is, that pytest checks whether the passed file does exist. A simple workaround could be to set the `__file__` variable to any existing file.

**Comment by neighthan** [comment] 2019-02-13 18:47
I just found your library and was also hoping to get rid of this requirement. I think a couple of viable options are

1. make a temporary file (e.g. using `tempfile`) and use its name. This ensures that the file exists, and it can be removed immediately after, so the cost should be minimal.

2. Use the name of the current notebook, as is done now, but get that name programmatically. [Here][link] is how I get notebook names, but I don't think there's an "official" way to do this, so it's possible that this approach will break in the future (I think somebody already noted that it doesn't work through JupyterHub).

I would probably favor option 1 because it seems less fragile than option 2. Any other options that are easier / more robust?

[link]: https://github.com/neighthan/jupyter-utils/blob/25b44b69559525e4bc7f1851c8cd3d87efe5365c/jupyter_utils/jupyter_utils.py#L12

**Comment by chmp** [comment] 2019-02-24 18:37
I like option 1, too, for similar reasons you mentioned. I implemented it in develop, you can give it a try by installing `ipytest==0.5.0b5`. To make `ipytest` fallback on the temporary file, you need to enable the `tempfile_fallback` option. My current setup reads:

```
import ipytest
ipytest.config(rewrite_asserts=True, tempfile_fallback=True, magics=True)
```

**Comment by chmp** [comment] 2019-03-14 23:29
In my experiments, the change worked quite well. I'll close the issue for now. Feel free to reopen, if anything comes up.

**Closed by chmp** 2019-03-14 23:29 UTC

**Comment by detly** [comment] 2019-08-01 05:31
I just had the same question, since I'm working on notebooks that I expect others to copy and work on separately, so they might rename it. Is there a reason you don't just make this the default behaviour?

**Comment by chmp** [comment] 2019-08-01 06:40
No real reason, what keeps me from making it a default atm:

1. I find it not very  aesthetic to create temporary files in the current working directory. But I am happy to put aesthetics aside for usability
2. Since I am not using this option all that often myself, I am not sure, whether there aren't any strange corner cases

Regarding 2: how is your experience with the `tempfile_fallback=True`? In any case, I will make an effort to use it more often in the coming days.

**Comment by detly** [comment] 2019-08-01 22:57
> I find it not very aesthetic to create temporary files in the current working directory. But I am happy to put aesthetics aside for usability

Does it need to be in `.`? IIRC, the default location for tempfiles is system dependent, and should usually be `/tmp` on Linux/FreeBSD and `%USERPROFILE%\AppData\Local\Temp` on Windows. But maybe there are problems with doing this in the context of the iPython kernel? 

My view is that either way, you'll have a slight wart: either the user needs an extra line in their notebook that might be a bit fragile, or you get a tempfile in the current dir. But with the latter, it will almost certainly disappear within a short period of time, and should only persist if there's a major problem with the kernel.

I haven't had any issues with it myself, but I haven't exactly put it through the mill. I will use it some more and let you know though.

(There is also an option #3, which is harder: try to figure out if Pytest itself can be tweaked to accommodate working without a real file. I am not in a position to volunteer to do this though :slightly_frowning_face:.)

**Comment by chmp** [comment] 2019-11-19 22:04
@detly after running with the `tempfile` option for a while now, I have been convinved. Mostly for symmetry reasons, I do not want to enable it by default (*). However, I added a `autoconfig` function with more reasonable defaults (`tempfile=True, magics=True, rewrite_asserts=True, addopts=['-q']`). Hopefully, this makes the library a bit smoother to use for you.

For now the option is only available in the current beta release. You can test-drive it by installing it with `pip install ipytest==0.8.0b1` and then use:

```python
import ipytest
ipytest.autoconfig()
```

(*): Since magics cannot be turned off, they should be optional, but then some options are enabled per default, some are disabled.
